language: python
python: 3.6.6
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coverage
  - pip install coveralls
  - pip install nose
script:
  - python test_Api.py
after_success:
  - coveralls
